# Generated by Django 4.2.2 on 2025-07-18 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="username",
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
    ]
