# Generated by Django 4.2.2 on 2025-07-18 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_username"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="username",
        ),
    ]
