# Generated by Django 4.2.2 on 2025-07-05 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AttemptMailing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "attempt_date",
                    models.DateField(verbose_name="Дата и время попытки отправки"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Successful", "Successful"),
                            ("Unsuccessful", "Unsuccessful"),
                        ],
                        max_length=20,
                    ),
                ),
                ("status_response", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Mailing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_first_sending",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата первой отправки"
                    ),
                ),
                (
                    "date_end_shipment",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата окончание отправки"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Completed", "Completed"),
                            ("Create", "Create"),
                            ("Running", "Running"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        verbose_name="Активность рассылки/Блокировка рассылки",
                    ),
                ),
            ],
            options={
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
                "permissions": [("block_mailing", "Блокировка рассылки")],
            },
        ),
    ]
