# Generated by Django 4.2.2 on 2025-07-05 13:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("message_manager", "0001_initial"),
        ("recipient_manager", "0001_initial"),
        ("mailing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mailing",
            name="mailing_owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Владелец рассылки",
            ),
        ),
        migrations.AddField(
            model_name="mailing",
            name="message",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="message_manager.message",
                verbose_name="Сообщение",
            ),
        ),
        migrations.AddField(
            model_name="mailing",
            name="recipient",
            field=models.ManyToManyField(to="recipient_manager.mailingrecipient"),
        ),
        migrations.AddField(
            model_name="attemptmailing",
            name="mailing",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="mailing.mailing",
                verbose_name="Рассылка",
            ),
        ),
    ]
