# Generated by Django 4.2.2 on 2025-07-19 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0002_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="mailing",
            old_name="mailing_owner",
            new_name="owner",
        ),
    ]
