# Generated by Django 4.2.2 on 2025-07-19 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0003_rename_mailing_owner_mailing_owner"),
    ]

    operations = [
        migrations.RenameField(
            model_name="mailing",
            old_name="owner",
            new_name="mailing_owner",
        ),
    ]
