# Generated by Django 4.2.2 on 2025-07-05 13:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("recipient_manager", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mailingrecipient",
            name="recipient_owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Владелец карточки клиента",
            ),
        ),
    ]
