# Generated by Django 4.2.2 on 2025-07-31 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipient_manager", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailingrecipient",
            options={
                "verbose_name": "Получатель рассылки",
                "verbose_name_plural": "Получатели рассылки",
            },
        ),
    ]
