# Generated by Django 4.2.2 on 2025-07-19 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("message_manager", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message",
            options={
                "ordering": ["subject"],
                "permissions": [
                    ("can_unpublish_message", "Can unpublish message"),
                    ("can_delete_message", "Can delete message"),
                ],
                "verbose_name": "Сообщение",
                "verbose_name_plural": "Сообщения",
            },
        ),
    ]
