# Generated by Django 4.2.2 on 2025-07-19 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("message_manager", "0003_alter_message_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message",
            options={"verbose_name": "Сообщение", "verbose_name_plural": "Сообщения"},
        ),
    ]
